
import type { Product, BlogPost, Testimonial } from '@/types';

export const mockProducts: Product[] = [
  // Agriculture Products
  {
    id: 'agri-1',
    name: 'De-Compose',
    description: 'An advanced bio-formulation to accelerate the decomposition of organic farm waste, turning it into nutrient-rich compost quickly. Ideal for breaking down crop residues, manure, and other organic materials, enriching your soil naturally.',
    price: 25.99,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Container of De-Compose',
    category: 'Agriculture',
    dataAiHint: 'compost accelerator',
    rating: 4.5,
    reviewCount: 120,
    availability: 'In Stock',
    features: [
      'Rapidly breaks down organic farm waste.',
      'Enriches soil with vital nutrients.',
      'Reduces waste volume significantly.',
      'Easy to apply formulation.',
      'Eco-friendly and sustainable solution.'
    ],
    howToUse: [
      'Prepare a 1:100 solution (1 part De-Compose to 100 parts water).',
      'Evenly spray the solution over the organic waste pile.',
      'Turn the pile weekly for optimal aeration and decomposition.',
      'Compost is typically ready in 4-6 weeks, depending on conditions.'
    ],
    ingredients: ['Consortium of cellulolytic and lignolytic microorganisms', 'Stabilizers', 'Carrier materials'],
    safetyInfo: 'Store in a cool, dry place away from direct sunlight. Keep out of reach of children. Wear gloves during application if sensitive skin.'
  },
  {
    id: 'agri-2',
    name: 'Bio fertilizer',
    description: 'A powerful blend of beneficial microbes that enhance soil fertility, improve nutrient uptake, and promote vigorous plant growth for various crops.',
    price: 18.50,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bag of Bio fertilizer',
    category: 'Agriculture',
    dataAiHint: 'fertilizer bag',
    rating: 4.2,
    reviewCount: 95,
    availability: 'In Stock',
    features: [
        'Boosts soil microbial activity.',
        'Improves nutrient availability to plants.',
        'Enhances root development.',
        'Suitable for a wide range of crops.'
    ],
    howToUse: 'Mix with soil during planting or top-dress around existing plants. Follow package instructions for specific crop application rates.',
    ingredients: ['Nitrogen-fixing bacteria (e.g., Azotobacter, Rhizobium)', 'Phosphate-solubilizing bacteria', 'Potash-mobilizing bacteria', 'Organic carrier material'],
  },
  {
    id: 'agri-3',
    name: 'Bio Fungicide',
    description: 'An organic solution to control and prevent fungal diseases in crops, ensuring healthier plants and better yields without harmful chemicals.',
    price: 22.00,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bottle of Bio Fungicide',
    category: 'Agriculture',
    dataAiHint: 'fungicide bottle',
    rating: 4.0,
    reviewCount: 78,
    availability: 'In Stock',
    features: [
        'Effective against common fungal pathogens.',
        'Safe for beneficial insects and pollinators.',
        'No chemical residues.',
        'Strengthens plant defense mechanisms.'
    ],
    howToUse: 'Dilute as per instructions and apply as a foliar spray or soil drench. Repeat applications as needed for disease prevention or control.',
    ingredients: ['Bacillus subtilis strains', 'Trichoderma species', 'Natural plant extracts with fungicidal properties'],
    safetyInfo: 'Avoid inhalation of spray mist. Wash hands after use.'
  },
  {
    id: 'agri-4',
    name: 'Bio Pesticide',
    description: 'Effectively manages a broad spectrum of agricultural pests using natural ingredients, safe for the environment and beneficial insects.',
    price: 20.75,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bottle of Bio Pesticide',
    category: 'Agriculture',
    dataAiHint: 'pesticide spray',
    rating: 3.9,
    reviewCount: 60,
    availability: 'Out of Stock',
    features: ['Broad-spectrum pest control.', 'Non-toxic to humans and pets when used as directed.', 'Biodegradable formulation.'],
    howToUse: 'Apply at first sign of pest infestation. Ensure thorough coverage of plant surfaces. Refer to label for specific pest instructions.',
    ingredients: ['Neem oil extract', 'Beauveria bassiana', 'Pyrethrins (from chrysanthemum flowers)'],
  },
  {
    id: 'agri-5',
    name: 'MYCO POWER',
    description: 'A mycorrhizal inoculant that establishes a symbiotic relationship with plant roots, greatly enhancing nutrient and water absorption.',
    price: 29.99,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Container of MYCO POWER',
    category: 'Agriculture',
    dataAiHint: 'mycorrhizal inoculant',
    rating: 4.8,
    reviewCount: 150,
    availability: 'In Stock',
    features: ['Increases root surface area.', 'Improves drought tolerance.', 'Enhances plant establishment.'],
    howToUse: 'Apply directly to roots during transplanting or mix into planting soil.',
    ingredients: ['Endomycorrhizal fungi spores', 'Ectomycorrhizal fungi spores', 'Bio-stimulants', 'Carrier material'],
  },
  {
    id: 'agri-6',
    name: 'Sea Wonder- Seaweed Extract',
    description: 'Concentrated seaweed extract rich in natural growth stimulants, trace elements, and vitamins to boost plant health and stress resistance.',
    price: 15.50,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bottle of Sea Wonder Seaweed Extract',
    category: 'Agriculture',
    dataAiHint: 'seaweed extract',
    rating: 4.6,
    reviewCount: 110,
    availability: 'In Stock',
    features: ['Rich in micronutrients and plant hormones.', 'Improves plant vigor and stress recovery.', 'Enhances fruit set and quality.'],
    howToUse: 'Dilute with water and apply as a foliar spray or soil drench. Suitable for all stages of plant growth.',
    ingredients: ['Concentrated Ascophyllum nodosum seaweed extract'],
  },
  {
    id: 'agri-7',
    name: 'Nature Choice',
    description: 'A versatile organic plant food suitable for a wide range of crops, providing balanced nutrition for optimal growth and productivity.',
    price: 17.00,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bag of Nature Choice plant food',
    category: 'Agriculture',
    dataAiHint: 'organic fertilizer',
    rating: 4.3,
    reviewCount: 88,
    availability: 'Pre-Order',
    features: ['Slow-release nutrients.', 'Improves soil structure.', 'Derived from natural sources.'],
    howToUse: 'Incorporate into soil before planting or use as a top dressing for established plants.',
    ingredients: ['Composted plant matter', 'Aged manure', 'Bone meal', 'Blood meal', 'Rock phosphate'],
  },
  {
    id: 'agri-8',
    name: 'SILICIC',
    description: 'A bio-available silicon supplement that strengthens plant cell walls, improves drought tolerance, and enhances resistance to pests and diseases.',
    price: 24.50,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Container of SILICIC supplement',
    category: 'Agriculture',
    dataAiHint: 'silicon supplement',
    rating: 4.7,
    reviewCount: 92,
    availability: 'In Stock',
    features: ['Strengthens plant tissues.', 'Increases resistance to lodging.', 'Improves nutrient uptake efficiency.'],
    howToUse: 'Add to nutrient solution or apply as a foliar spray according to product guidelines.',
    ingredients: ['Stabilized silicic acid', 'Micronutrients'],
  },
  {
    id: 'agri-9',
    name: 'Palm Nutrients',
    description: 'Specially formulated nutrient mix to meet the specific dietary requirements of palm trees, promoting lush fronds and healthy growth.',
    price: 21.00,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bag of Palm Nutrients',
    category: 'Agriculture',
    dataAiHint: 'palm fertilizer',
    rating: 4.4,
    reviewCount: 70,
    availability: 'In Stock',
    features: ['Balanced NPK ratio for palms.', 'Contains essential micronutrients like magnesium and manganese.', 'Promotes deep green frond color.'],
    howToUse: 'Apply around the base of palm trees, avoiding direct contact with the trunk. Water thoroughly after application.',
    ingredients: ['Nitrogen, Phosphorus, Potassium sources', 'Magnesium sulfate', 'Manganese sulfate', 'Iron chelates'],
  },

  // Gardening Products
  {
    id: 'gard-1',
    name: 'Enriched Cocopeat',
    description: 'High-quality cocopeat block, enriched with essential nutrients. Provides excellent aeration and water retention for potting mixes.',
    price: 8.99,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Block of Enriched Cocopeat',
    category: 'Gardening Products',
    dataAiHint: 'cocopeat block',
    rating: 4.5,
    reviewCount: 180,
    availability: 'In Stock',
    features: ['Sustainable and renewable resource.', 'Neutral pH.', 'Improves soil structure.'],
    howToUse: 'Soak the cocopeat block in water until it expands. Mix with other soil amendments or use as a standalone growing medium.',
    ingredients: ['Dehydrated coconut coir pith', 'Slow-release NPK fertilizer'],
  },
  {
    id: 'gard-2',
    name: 'Vermiculite',
    description: 'A natural mineral that improves soil aeration and moisture retention. Ideal for seed starting and conditioning potting mixes.',
    price: 10.50,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bag of Vermiculite',
    category: 'Gardening Products',
    dataAiHint: 'vermiculite bag',
    rating: 4.3,
    reviewCount: 130,
    availability: 'In Stock',
    features: ['Lightweight and sterile.', 'Excellent for seed germination.', 'Helps prevent soil compaction.'],
    howToUse: 'Mix with potting soil or peat moss to improve aeration and water retention. Can also be used as a top layer for seed starting.',
    ingredients: ['Exfoliated vermiculite mineral'],
  },
  {
    id: 'gard-3',
    name: 'Perlite',
    description: 'Lightweight volcanic glass that enhances drainage and aeration in soil, preventing compaction and promoting healthy root growth.',
    price: 9.75,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bag of Perlite',
    category: 'Gardening Products',
    dataAiHint: 'perlite bag',
    rating: 4.2,
    reviewCount: 145,
    availability: 'In Stock',
    features: ['Improves drainage significantly.', 'Prevents waterlogging.', 'Encourages strong root systems.'],
    howToUse: 'Add to potting mixes for plants that require excellent drainage, such as succulents and cacti. Typically 10-30% of the mix.',
    ingredients: ['Expanded perlite (volcanic glass)'],
  },
  {
    id: 'gard-4',
    name: 'Phytosil',
    description: 'A silicon-based soil conditioner and plant health booster for home gardens. Strengthens plants against stress and diseases.',
    price: 16.00,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bottle of Phytosil',
    category: 'Gardening Products',
    dataAiHint: 'plant supplement',
    rating: 4.7,
    reviewCount: 90,
    availability: 'In Stock',
    features: ['Enhances plant structural integrity.', 'Improves resistance to pests and diseases.', 'Boosts overall plant health.'],
    howToUse: 'Mix with water according to label instructions and apply as a soil drench or foliar spray.',
    ingredients: ['Potassium silicate', 'Trace elements'],
  },
  {
    id: 'gard-5',
    name: 'Organic health booster',
    description: 'A comprehensive organic mix to revitalize garden soil and boost plant vitality, packed with micronutrients and beneficial microbes.',
    price: 14.99,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bag of Organic health booster',
    category: 'Gardening Products',
    dataAiHint: 'soil amendment',
    rating: 4.6,
    reviewCount: 210,
    availability: 'In Stock',
    features: ['Rich in humus and organic matter.', 'Contains a diverse range of beneficial microorganisms.', 'Improves soil fertility and plant resilience.'],
    howToUse: 'Incorporate into garden beds before planting or top-dress around existing plants. Can also be used to enrich potting mixes.',
    ingredients: ['Composted manures', 'Worm castings', 'Kelp meal', 'Fish meal', 'Humic acids'],
  },
  {
    id: 'gard-6',
    name: 'Vermicompost',
    description: 'Nutrient-rich organic compost created by earthworms. Excellent for improving soil structure and providing essential plant nutrients.',
    price: 12.50,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bag of Vermicompost',
    category: 'Gardening Products',
    dataAiHint: 'worm castings',
    rating: 4.9,
    reviewCount: 250,
    availability: 'In Stock',
    features: ['High in beneficial microbes.', 'Improves soil aeration and water retention.', 'Gentle on plants, will not burn roots.'],
    howToUse: 'Use as a soil amendment, top dressing, or ingredient in potting mixes. Can also be brewed into a compost tea.',
    ingredients: ['100% Pure Earthworm Castings'],
  },
  {
    id: 'gard-7',
    name: 'Grow cubes',
    description: 'Convenient, pre-formed cubes made of high-quality substrate, perfect for seed starting and rooting cuttings with minimal mess.',
    price: 7.50,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Pack of Grow cubes',
    category: 'Gardening Products',
    dataAiHint: 'seed starters',
    rating: 4.0,
    reviewCount: 100,
    availability: 'Out of Stock',
    features: ['Provides optimal moisture and aeration for germination.', 'Easy to transplant seedlings.', 'Reduces transplant shock.'],
    howToUse: 'Moisten cubes thoroughly before sowing seeds or inserting cuttings. Keep moist until roots develop.',
    ingredients: ['Compressed peat moss or coco coir', 'Wetting agent'],
  },
  {
    id: 'gard-8',
    name: 'Rose mixture',
    description: 'A specialized blend of organic ingredients tailored to the needs of rose plants, promoting abundant blooms and vigorous growth.',
    price: 13.75,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bag of Rose mixture',
    category: 'Gardening Products',
    dataAiHint: 'rose fertilizer',
    rating: 4.5,
    reviewCount: 160,
    availability: 'In Stock',
    features: ['Formulated for heavy-feeding roses.', 'Encourages strong canes and vibrant flowers.', 'Contains essential nutrients and organic matter.'],
    howToUse: 'Apply around the base of rose bushes in early spring and after each bloom cycle. Water in well.',
    ingredients: ['Alfalfa meal', 'Bone meal', 'Blood meal', 'Fish meal', 'Sulfate of potash', 'Compost'],
  },
  {
    id: 'gard-9',
    name: 'Garden Mix',
    description: 'A ready-to-use premium soil mix for all your gardening needs, perfect for pots, raised beds, and garden plots. Promotes healthy plant growth.',
    price: 11.99,
    imageSrc: 'https://placehold.co/600x400.png',
    imageAlt: 'Bag of Garden Mix soil',
    category: 'Gardening Products',
    dataAiHint: 'potting soil',
    rating: 4.4,
    reviewCount: 190,
    availability: 'In Stock',
    features: ['Balanced for general garden use.', 'Good drainage and aeration.', 'Contains starter nutrients.'],
    howToUse: 'Use directly in containers, raised beds, or to amend existing garden soil.',
    ingredients: ['Aged forest products', 'Peat moss', 'Compost', 'Perlite or pumice', 'Organic fertilizers'],
  }
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    slug: 'getting-started-with-organic-gardening',
    title: 'Getting Started with Organic Gardening: A Beginner\'s Guide',
    excerpt: 'Discover the joys of organic gardening! This guide covers the basics, from soil preparation to choosing the right plants for your eco-friendly garden.',
    imageSrc: 'https://placehold.co/800x450.png',
    imageAlt: 'Lush organic vegetable garden',
    dataAiHint: 'organic garden',
    date: '2024-05-15T10:00:00Z',
    author: 'Jane GreenThumb',
    content: 'Organic gardening is more than just a trend; it’s a commitment to sustainable practices and healthier living. This guide will walk you through the essentials to start your own organic garden, no matter the size of your space.\\n\\nFirst, understand your soil. Healthy soil is the cornerstone of organic gardening. Get a soil test to understand its pH and nutrient levels. Amend your soil with compost and other organic matter to improve its structure and fertility. BioWe offers excellent organic compost to get you started!\\n\\nNext, choose your plants wisely. Opt for native plants or varieties well-suited to your climate. This reduces the need for excessive watering and pest control. Consider companion planting to naturally deter pests and enhance growth. For example, basil planted near tomatoes can repel certain insects and improve tomato flavor.\\n\\nWatering effectively is crucial. Water deeply but infrequently to encourage strong root development. Morning is the best time to water, as it allows leaves to dry during the day, reducing the risk of fungal diseases.\\n\\nFinally, embrace natural pest and disease control. Encourage beneficial insects like ladybugs and lacewings. Use physical barriers or organic sprays like neem oil if pests become a problem. BioWe’s Eco-Friendly Pest Control Spray is a great option. Happy gardening!',
  },
  {
    id: '2',
    slug: 'top-5-fertilizers-for-vibrant-blooms',
    title: 'Top 5 BioWe Fertilizers for Vibrant Blooms',
    excerpt: 'Unlock the secret to stunning flowers with our top-rated organic fertilizers. Learn which BioWe product is perfect for your blooming beauties.',
    imageSrc: 'https://placehold.co/800x450.png',
    imageAlt: 'Colorful flowers blooming in a garden',
    dataAiHint: 'colorful flowers',
    date: '2024-05-22T14:30:00Z',
    author: 'Alex Roots',
    content: 'Every gardener dreams of a profusion of vibrant blooms. The key? The right nutrition. At BioWe, we’ve formulated a range of organic fertilizers to help your flowering plants thrive. Here are our top 5 picks:\\n\\n1. BioWe Organic Bloom Booster: Specially designed to enhance flowering and fruiting. Rich in phosphorus and potassium, it encourages abundant, long-lasting blooms.\\n\\n2. BioWe All-Purpose Plant Food: A balanced fertilizer that supports overall plant health, leading to stronger stems and more resilient flowers. Great for a wide variety of flowering annuals and perennials.\\n\\n3. BioWe Rose & Flower Care: Tailored for roses and other demanding flowering shrubs, this mix promotes brilliant colors and healthy foliage.\\n\\n4. BioWe Liquid Seaweed Extract: A fantastic supplement that provides trace minerals and growth hormones, acting as a biostimulant for impressive floral displays.\\n\\n5. BioWe Bone Meal: A natural source of phosphorus, essential for root development and flower production. Incorporate it into the soil when planting or as a top dressing for established plants.\\n\\nRemember to follow application instructions for each product to achieve the best results. With BioWe, your garden will be the envy of the neighborhood!',
  },
  {
    id: '3',
    slug: 'container-gardening-tips-for-small-spaces',
    title: 'Container Gardening Magic: Tips for Small Spaces',
    excerpt: 'No backyard? No problem! Explore creative container gardening ideas to grow your own food and flowers, even on a balcony or patio.',
    imageSrc: 'https://placehold.co/800x450.png',
    imageAlt: 'Assortment of plants in pots on a balcony',
    dataAiHint: 'balcony garden',
    date: '2024-06-01T09:15:00Z',
    author: 'Sarah Sprouts',
    content: 'Living in an apartment or home with limited outdoor space doesn’t mean you have to give up on your gardening dreams. Container gardening offers a fantastic way to cultivate plants on balconies, patios, or even sunny windowsills.\\n\\nChoose the right containers. Ensure they have adequate drainage holes. The size of the container should match the mature size of the plant. Materials vary from terracotta (dries out faster) to plastic (retains moisture longer) and fabric pots (excellent aeration). BioWe offers a range of stylish and functional self-watering planters.\\n\\nUse quality potting mix. Don’t use garden soil in containers, as it compacts easily. BioWe Premium Potting Mix is specifically formulated for container gardening, providing good drainage and aeration while retaining necessary moisture and nutrients.\\n\\nSelect appropriate plants. Many vegetables, herbs, and flowers thrive in containers. Consider dwarf varieties of your favorite plants. Herbs like basil, mint, and rosemary are excellent choices, as are compact tomatoes, peppers, and lettuce. For flowers, try petunias, geraniums, or succulents.\\n\\nWatering and fertilizing. Container plants dry out more quickly than those in the ground, so monitor moisture levels regularly. Fertilize as needed, as nutrients can leach out with watering. BioWe’s liquid fertilizers are easy to apply for container plants.\\n\\nMaximize your space. Use vertical planters, hanging baskets, and tiered shelving to make the most of your small area. With a little creativity, your small space can become a green oasis!',
  },
  {
    id: '4',
    slug: 'understanding-soil-health',
    title: 'The Dirt on Soil: Understanding Soil Health for a Thriving Garden',
    excerpt: 'Healthy soil is the foundation of a successful garden. Learn about soil composition, amendments, and how BioWe products can help improve your soil structure.',
    imageSrc: 'https://placehold.co/800x450.png',
    imageAlt: 'Close up of rich, dark garden soil',
    dataAiHint: 'garden soil',
    date: '2024-06-10T11:00:00Z',
    author: 'Mike Gardener',
    content: 'Often overlooked, soil is the single most important ingredient for a flourishing garden. Understanding and nurturing your soil’s health will pay dividends in the form of robust plants and bountiful harvests.\\n\\nSoil is a living ecosystem, teeming with microorganisms, fungi, and earthworms that break down organic matter and make nutrients available to plants. Good soil structure allows for proper aeration, drainage, and root penetration.\\n\\nKey components of healthy soil include: Organic Matter (compost, manure, leaf mold), Minerals (sand, silt, clay), and Pore Spaces (for air and water). The ideal soil, often called loam, has a balanced mix of these.\\n\\nHow to improve your soil? Add organic matter regularly. Compost is king! It improves soil structure, water retention, and nutrient content. BioWe’s Premium Potting Mix and Organic Bloom Booster are excellent sources of organic matter for different needs. Avoid tilling excessively, as it can damage soil structure and harm beneficial organisms. Consider cover crops like clover or rye during the off-season to prevent erosion and add organic matter when tilled in.\\n\\nMulching is another great practice. A layer of organic mulch (wood chips, straw, shredded leaves) helps retain moisture, suppress weeds, and regulate soil temperature. As it decomposes, it also adds organic matter to the soil.\\n\\nBy focusing on building healthy soil, you’re creating a sustainable foundation for your garden to thrive for years to come. BioWe is here to support your journey to better soil and better gardening!',
  },
];


export const mockTestimonials: Testimonial[] = [
  {
    id: 'testimonial-1',
    quote: "BioWe's De-Compose turned my kitchen scraps into black gold faster than I ever thought possible! My veggies have never been happier.",
    author: 'Maria S.',
    role: 'Home Gardener',
    avatarSrc: 'https://placehold.co/100x100.png',
    dataAiHint: 'happy person'
  },
  {
    id: 'testimonial-2',
    quote: "Since using MYCO POWER on my crops, I've seen a significant increase in yield and resilience, even during dry spells. Highly recommend for serious farmers.",
    author: 'John B.',
    role: 'Commercial Farmer',
    avatarSrc: 'https://placehold.co/100x100.png',
    dataAiHint: 'farmer field'
  },
  {
    id: 'testimonial-3',
    quote: "The Organic Health Booster revived my struggling flower beds! The colors are more vibrant, and the plants look so much healthier. Thank you, BioWe!",
    author: 'Lisa P.',
    role: 'Flower Enthusiast',
    avatarSrc: 'https://placehold.co/100x100.png',
    dataAiHint: 'smiling woman'
  },
];
